"""adding time table in user final

Revision ID: 099c16da15a0
Revises: b2a8981c50fe
Create Date: 2026-06-18 20:52:06.106930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099c16da15a0'
down_revision: Union[str, Sequence[str], None] = 'b2a8981c50fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Buy', sa.Column('OrderedAt', sa.TIMESTAMP(timezone=True), nullable=False, server_defaults=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Buy', 'OrderedAt')
    # ### end Alembic commands ###
