"""final model

Revision ID: 12d14d1c2fdb
Revises: a19a6e071dfe
Create Date: 2026-06-16 22:23:56.487578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d14d1c2fdb'
down_revision: Union[str, Sequence[str], None] = 'a19a6e071dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('currentsellerid', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Inventory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currentsellerid'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productid'], ['product.productId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('productid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###
