"""adding Otp to db

Revision ID: 1f87918eb067
Revises: d37a30ad0758
Create Date: 2026-06-19 21:08:14.918491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f87918eb067'
down_revision: Union[str, Sequence[str], None] = 'd37a30ad0758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordreset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['useremail'], ['user.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwordreset')
    # ### end Alembic commands ###
