"""adding new table

Revision ID: 489cfc983884
Revises: 8a9a69f44b2e
Create Date: 2026-06-16 15:52:08.677644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489cfc983884'
down_revision: Union[str, Sequence[str], None] = '8a9a69f44b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentsellerid', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('Inventory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currentsellerid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    # ### end Alembic commands ###
