"""adding bought

Revision ID: 84c513d1ba3f
Revises: 93cb6c8bd5d0
Create Date: 2026-06-18 17:47:18.501228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c513d1ba3f'
down_revision: Union[str, Sequence[str], None] = '93cb6c8bd5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productid'], ['product.productId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Buy')
    # ### end Alembic commands ###
