"""adding user and seller data

Revision ID: 8a9a69f44b2e
Revises: b8a590581ae6
Create Date: 2026-06-14 18:53:13.884410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9a69f44b2e'
down_revision: Union[str, Sequence[str], None] = 'b8a590581ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellerprofile',
    sa.Column('currentsellerid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GSTNo', sa.String(), nullable=False),
    sa.Column('CompanyName', sa.String(), nullable=False),
    sa.Column('OwnerName', sa.String(), nullable=False),
    sa.Column('Address', sa.String(), nullable=False),
    sa.Column('Pincode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['currentsellerid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userprofile',
    sa.Column('currentuserid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['currentuserid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofile')
    op.drop_table('sellerprofile')
    # ### end Alembic commands ###
