""" adding cart

Revision ID: 93cb6c8bd5d0
Revises: 12d14d1c2fdb
Create Date: 2026-06-17 21:36:30.663510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cb6c8bd5d0'
down_revision: Union[str, Sequence[str], None] = '12d14d1c2fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myCart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('img1', sa.String(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productid'], ['product.productId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myCart')
    # ### end Alembic commands ###
