"""adding product id table in warehouse

Revision ID: a19a6e071dfe
Revises: 489cfc983884
Create Date: 2026-06-16 18:16:54.903118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19a6e071dfe'
down_revision: Union[str, Sequence[str], None] = '489cfc983884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('productid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'warehouse', 'product', ['productid'], ['productId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'productid')
    # ### end Alembic commands ###
