"""create product table

Revision ID: b8a590581ae6
Revises: a51b70c5ced1
Create Date: 2026-06-14 11:18:21.052411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a590581ae6'
down_revision: Union[str, Sequence[str], None] = 'a51b70c5ced1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('sellerid', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('ProductDescription', sa.String(), nullable=False),
    sa.Column('img1', sa.String(), nullable=False),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('video1', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sellerid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
