"""adding orderid

Revision ID: d37a30ad0758
Revises: 3290f748fa04
Create Date: 2026-06-19 17:20:13.674668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37a30ad0758'
down_revision: Union[str, Sequence[str], None] = '3290f748fa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Buy', sa.Column('OrderId', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Buy', 'OrderId')
    # ### end Alembic commands ###
